# --- Plug by SIEM, Do Not MODIFY
PROMPT_COMMAND="history -a; history -n"
export HISTSIZE=$HITSIZE
export HISTTIMEFORMAT=$HISTTIMEFORMAT 
export HISTCONTROL=$HISTCONTROL
export HISTIGNORE=$HISTIGNORE
# --- End of Plug